<a href="https://colab.research.google.com/github/Phanuwat-S-S/229352-StatisticalLearning2/blob/main/Lab07_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [4]:
x = torch.tensor(5)
print(x)
print(x.shape)

tensor(5)
torch.Size([])


### Convert a tensor to scalar

In [5]:
scalar = x.item()
print(scalar)
print(type(scalar))

5
<class 'int'>


### Creating 2D tensor

In [6]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(A)
print(A.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


## Tensor and Numpy

### Convert from tensor to numpy array

In [7]:
A_np = A.numpy()
print(A_np)
print(type(A_np))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### Convert from numpy array to tensor

In [8]:
B = np.array([[7, 8], [9, 10]])
B_tensor = torch.from_numpy(B)
print(B_tensor)
print(type(B_tensor))

tensor([[ 7,  8],
        [ 9, 10]])
<class 'torch.Tensor'>


## PyTorch and GPU

check if GPU is available

In [9]:
torch.cuda.is_available()

True

In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
A = A.to(device)
print(A.device)

cuda:0


## Basic operations

### Matrix multiplication

In [12]:
A = torch.randn(3, 4)
B = torch.randn(4, 2)
C = torch.matmul(A, B)
print(C)

tensor([[-0.8146, -1.0335],
        [ 0.8908, -0.8614],
        [-1.1515, -0.8014]])


### Matrix transpose

In [13]:
A_T = A.T
print(A_T)

tensor([[ 2.2948, -0.2860,  0.8518],
        [-0.4609, -0.6210,  0.7910],
        [-0.7929,  2.4081, -0.4860],
        [ 0.8876, -1.1814,  0.6463]])


## Creating a specific type of tensor

In [14]:
zeros = torch.zeros(3, 3)
ones = torch.ones(2, 4)
rand = torch.randn(2, 2)

print(zeros)
print(ones)
print(rand)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[ 0.4181, -1.0021],
        [-0.2970,  1.3225]])


## Tensor's shape

### Checking the shape of a tensor

In [15]:
X = torch.randn(5, 3)
print(X.shape)

torch.Size([5, 3])


### Changing the shape of a tensor

In [16]:
X_reshape = X.reshape(3, 5)
print(X_reshape)

tensor([[-0.8343, -0.3300, -1.2297, -0.6447,  0.9494],
        [-0.9561,  0.4161,  0.7289, -1.8122, -0.5274],
        [-0.2061, -1.4596,  0.2712,  0.6508,  0.6434]])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [17]:
A = torch.tensor([1, 2, 3])
B = torch.tensor([4, 5, 6])

stacked = torch.stack((A, B))
print(stacked)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
# concatenate
concat = torch.cat((A, B))
print(concat)

tensor([1, 2, 3, 4, 5, 6])


### Squeezing a tensor (removing an extra dimension)

In [19]:
X = torch.randn(1, 3, 1)
print(X.shape)

X_squeezed = X.squeeze()
print(X_squeezed.shape)

torch.Size([1, 3, 1])
torch.Size([3])


### Unsqueezing a tensor (adding an extra dimension)

In [20]:
# H.shape = (6, )
X_unsqueezed = X_squeezed.unsqueeze(0)
print(X_unsqueezed.shape)

torch.Size([1, 3])


## Indexing

In [24]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [25]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [26]:
# 1.
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

# 2.
ones = torch.ones(200, 1)

# 3.
X = torch.cat((ones, X), dim=1)

# 4.
y = torch.matmul(X, b) + e

# 5.
XtX = torch.matmul(X.T, X)
XtX_inv = torch.inverse(XtX)
Xt_y = torch.matmul(X.T, y)
b_hat = torch.matmul(XtX_inv, Xt_y)

# 6.
y_hat = torch.matmul(X, b_hat)

# 7.
y_np = y.detach().numpy()
y_hat_np = y_hat.detach().numpy()

MSE = np.mean((y_np - y_hat_np) ** 2)
print("MSE:", MSE)

MSE: 1.0708518
